InconfontFlag: true
debug: false
replace:

csp:
  enable: false

default:
  avatar: /img/default/avatar.svg
  link: /img/default/link.svg
  cover: /img/default/cover.svg
  image: /img/default/image.svg

cdn_system:
  system_config:
    custom:
      busuanzi: /js/bsz.js

nextNavbar:
  subtitle: 繁星永存，记忆亘古不变。
  menu:
    - name: '- 首页 °| Home'
      icon: 'fa-light fa-home'
      url: /
    - name: '- 笔记 °| Notes'
      icon: 'fa-light fa-notebook'
      url: /page/notes/
    - name: '- 归档 °| Archives'
      icon: 'fa-light fa-archive'
      url: /archives/
    - name: '- 留言 °| Message'
      icon: 'fa-light fa-object-group'
      url: /page/info/
    - name: '- 友链 °| Friends'
      icon: 'fa-light fa-link'
      url: /page/friends/
    - name: '- 生活 °| Blogger'
      icon: 'fa-light fa-ghost'
      url: https://szyink.com/
    - name: '- 虫洞 °| Wormhole'
      icon: 'fa-light fa-bullseye-pointer'
      url: https://www.foreverblog.cn/go.html
      target: '_blank'  
    - name: '- 搜索 °| Search'
      icon: 'fa-light fa-search'
      url: 'javascript:void(0)'
      click: 'OpenSearch()'

cover:
  enable: true
  height_scheme: blank
  layout_scheme: dock
  display:
    home: false
    archive: false
    others: false
  background: /img/wallhaven-j31omy.jpg
  title: '枋柚梓'
  subtitle: '繁星永存 记忆亘古不变'
  search: '想找些什么？'
  features:
    - name: 首页
      icon: fa-light fa-home CARROT 
      url: /
    - name: 笔记
      icon: fa-light fa-notebook NEPHRITIS
      url: /page/notes/
    - name: 归档
      icon: fa-light fa-archive ASBESTOS
      url: /archives/
    - name: 关于
      icon: fa-light fa-drafting-compass WETASPHALT
      url: /page/about/
    - name: 友链
      icon: fa-light fa-link POMEGRANATE
      url: /page/friends/

navbar:
  enable: true
  visiable: always
  logo:
    img: /icon/favicon.svg
    title: '枋柚梓的猫会发光'
  menu:
    - name: 首页
      icon: fa-light fa-home CARROT faa-vertical
      url: /
    - name: 导航
      icon: fa-light fa-cube NEPHRITIS
      rows:
        - name: 分类列表
          icon: fa-light fa-folder-open ALIZARIN faa-vertical
          url: /categories/
        - name: 文章标签
          icon: fa-light fa-tags PETERRIVE faa-vertical
          url: /tags/
    - name: 页面
      icon: fa-light fa-anchor GREENSEA faa-vertical
      rows:
        - name: 站内留言
          icon: fa-light fa-object-group ALIZARIN faa-vertical
          url: /page/info/
        - name: RSS 订阅
          icon: fa-light fa-rss SUNFLOWER faa-vertical
          url: /page/atom/
        - name: 授权协议
          icon: fa-light fa-universal-access SUNFLOWER faa-vertical
          url: /page/policy/
        - name: 建站历史
          icon: fa-light fa-history ALIZARIN faa-vertical
          url: /page/timeline/
    - name: 更多
      icon: fa-light fa-umbrella POMEGRANATE faa-vertical
      description: 站外资源列表
      rows:
        - name: BT 
          description: 宝塔面板
          icon: fa-light fa-command BELIZEHOLE faa-vertical
          url: https://web.adc.ink/
        - name: Cloud
          description: 可道云
          icon: fa-light fa-cloud WISTERIA faa-vertical
          url: https://cloud.adc.ink/
        - name: Umami
          icon: fa-light fa-compass-drafting PETERRIVE faa-vertical
          description: 访问量统计
          url: https://um.adc.ink/share/sKrpXWfJ/%E6%9E%8B%E6%9F%9A%E6%A2%93%E7%9A%84%E7%8C%AB%E4%BC%9A%E5%8F%91%E5%85%89
        - name: Uptime
          icon: fa-light fa-route-interstate PETERRIVE faa-vertical
          description: 服务状态监控
          url: https://ut.adc.ink/status/me
        - name: Github
          description: 少年，来一份星星不？
          icon: fa-light fa-code-merge WISTERIA faa-vertical
          url: https://github.com/inkss
    - name: 生活
      description: 这是一份记录文字的博客站点
      icon: fa-light fa-ghost BELIZEHOLE faa-vertical
      url: https://szyink.com
    - name: 虫洞
      description: 十年之约，探索虫洞
      icon: fa-light fa-bullseye-pointer BELIZEHOLE faa-vertical
      url: https://www.foreverblog.cn/go.html
  search: Search...   # Search bar placeholder

pages:
  friends:
    layout_scheme: traditional 

article:
  preview:
    line_style: hidden
  body:
    top_meta: [author, wordcount, artalkcount]
    bottom_meta: [category, tags, counter]
    meta_library:
      author:
        avatar: https://static.inkss.cn/img/avatar.png
        name: 枋柚梓
        url: /
      date:
        icon: fa-light fa-calendar-alt TURQUOISE
      updated:
        icon: fa-light fa-edit GREENSEA
      category:
        icon: fa-light fa-folder-open EMERALD
      counter:
        icon: fa-light fa-eye NEPHRITIS
      walinecount:
        icon: fa-light fa-comment-dots NEPHRITIS
      artalkcount:
        icon: fa-light fa-comment-dots NEPHRITIS
        desc: '条评论' # 条评论
      wordcount:
        icon_wordcount: fa-light fa-keyboard PETERRIVE
        icon_duration: fa-light fa-hourglass-half BELIZEHOLE
      tags:
        icon: fa-light fa-hashtag CARROT
    footer_widget:
      references:
        icon: fa-light fa-quote-left CONCRETE
      copyright:
        enable: true
        content:
          - '博客内容遵循 <a href="/page/cc">署名-非商业性使用-相同方式共享 4.0 国际</a> 协议。'
        custom: true # 开启后替代上方内容的版权显示
        customData:
          default: type1  # 默认授权声明
          rules:
            adapt:
              text: 原作许可协议
              desc: 本文演绎自他站，转载或引用本文时，请遵守原作许可协议！

comments:
  title: <i class='fa-light fa-comments POMEGRANATE'></i> 评论
  disqus:
    shortname: inkss
    autoload: true
  beaudar:
    repo: inkss/blog-comments
    branch: master
  artalk:
    server: https://artalk.szyink.com

sidebar:
  position: right # left right
  for_page: [nextsite, nextblogger, tagcloud]
  for_post: [nextsite, nextblogger, toc, webinfo]
  widget_library:
    nextblogger:
      class: nextblogger
      display: [desktop] # [desktop, mobile]
      avatar: /img/avatar.png
      url: /page/about/
      subtitle: 言语道断，非物所拘。
      lists:
        - url: https://github.com/inkss
          icon: fa-brands fa-github
          title: Github
        - url: /page/atom/
          icon: fa-solid fa-rss
          title: RSS
        - url: /page/timeline/
          icon: fa-solid fa-history
          title: History  
        - url: https://ut.adc.ink/status/me
          icon: fa-solid fa-eye
          title: Status
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: /img/avatar.png
      shape: circle # circle, rectangle
      url: /page/about/
      title:
      subtitle: 言语道断，非物所拘。
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
    lastupdate:
      class: lastupdate
      display: [desktop]
      header:
        icon: fa-light fa-clock WISTERIA
        title: 最近更新
    toc:
      display: [desktop, mobile]
      header:
        icon: fa-light fa-list ASBESTOS
    category:
      display: [desktop]
      header:
        icon: fa-light fa-folder-open ASBESTOS
        url: /categories/
    tagcloud:
      display: [desktop]
      header:
        title: 标签列表
        icon: fa-light fa-tags WISTERIA 
        url: /tags/
      max_font: 18
      min_font: 14
    webinfo:
      display: [desktop]
      header:
        icon: fa-light fa-award NEPHRITIS
      type:
        runtime:
          enable: true
          data: '2018/03/15'
        wordcount:
          unit: ''
          enable: true
        visitcounter:
          enable: false
    notice:
      sticky: true
      class: text
      display: [desktop, mobile]
      header:
        icon: fa-light fa-ghost PETERRIVE 
        title: 公共信息
      content:
        - '欢迎访问，祝您身心愉悦。'
        - '本站托管于 Github Page。'
    updateList:
      class: text
      display: [desktop]
      header:
        icon: fa-light fa-wrench SUNFLOWER 
        title: 更新日志
      content:
        - 暂无 
    navigation:
      class: grid
      display: [desktop]
      header:
        icon: fa-light fa-map-signs POMEGRANATE 
        title: 站内导航
      fixed: true # 固定宽度
      rows:
        - name: 首页
          icon: fa-light fa-home
          url: /
        - name: 笔记
          icon: fa-light fa-notebook
          url: /page/notes/
        - name: 归档
          icon: fa-light fa-archive
          url:  /archives/
        - name: 留言
          icon: fa-light fa-object-group
          url: /page/info/
        - name: 友链
          icon: fa-light fa-link
          url: /page/friends/
        - name: 订阅
          icon: fa-light fa-rss
          url: /page/atom/
    artalk:
      class: artalk
      sticky: true
      display: [desktop]
    nextsite:
      class: nextsite
      display: [desktop, mobile]
    started:
      class: list
      display: [desktop]
      sticky: true
      header:
        icon: fa-light fa-thumbs-up WISTERIA
        title: 推荐阅读
      rows:
        - name: • uBlacklist：拯救你的搜索结果
          url: /post/8204c0ab/
        - name: • 自动化博客部署
          url: /post/42987b6b/
        - name: • 原生 JS 的右键菜单实现
          url: /post/3717f151/
        - name: • 微信小程序之订阅消息
          url: /post/5e967ba/  
        - name: • 记标签页与路由联动的处理方案
          url: /post/dfbd179/  
        - name: • Ant Design 快速上手系列
          url: /post/8ab78feb/  
        - name: • 泛域名解析配置
          url: /post/e7617c8b/  
    notes: 
      sticky: true
      class: group
      display: [desktop, mobile]
      seo_title: 文章笔记
      url: /page/notes/
      header:
        icon: fa-light fa-notebook PETERRIVE
        title: 文章笔记

tag_plugins:
  note:
    iconfont: 'Font Awesome 6 Pro'
  link:
    placeholder:  /img/default/chrome.png

site_footer:
  layout: [copyright, powered]
  icon: '<i class="fa-light fa-heartbeat POMEGRANATE faa-flash faa-slow animated"></i>'
  copyright: '<span>© 2018 - 2023&nbsp;</span><span><i class="fa-light fa-heartbeat POMEGRANATE faa-flash faa-slow animated"></i></span><span>&nbsp;枋柚梓</span>'
  powered: '<a href="/page/policy/">政策</a> · <a href="https://um.adc.ink/share/sKrpXWfJ/%E6%9E%8B%E6%9F%9A%E6%A2%93%E7%9A%84%E7%8C%AB%E4%BC%9A%E5%8F%91%E5%85%89">统计</a> | 本站使用 <a href="https://volantis.js.org/" target="_blank">Volantis</a> 主题设计'

plugins:
  busuanzi:
    enable: true
  wordcount:
    enable: true
  lazyload:
    enable: false
    onlypost: false
  aplayer:
    enable: false
    server: tencent
    id: 7716882294
  pjax:
    enable: false
    cover: false
  sitesjs:
    enable: false
  friendsjs:
    enable: false
  contributorsjs:
    enable: false
  preload:
    enable: false
    service: instant_page
  scrollreveal:
    enable: false
  nodewaves:
    enable: false
  fontawesome_animation:
    enable: false
  killOldVersionsOfIE:
    enable: false
  killNoScript:
    enable: false
  darkmode:
    enable: true
  darkmodejs:
    enable: true
  tag_plugin_load_on_demand:
    enable: false
  message:
    enable: false
    icon:
      default: fa-light fa-info-circle light-blue
      quection: fa-light fa-question-circle light-blue
    copyright:
      enable: false
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'fa-brands fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red
    rightmenu:
      enable: true
      notice: true
  parallax:
    enable: false
    fade: 1000
    images:
      - /img/wallhaven-j31omy.jpg

rightmenus:
  enable: true
  order:
    - plugins.navigation  
    - hr
    - plugins.inputBox
    - plugins.seletctText
    - hr
    - plugins.elementCheck
    - plugins.elementImage
    - menus.prevNext
    - hr
    - menus.links
    - hr
    - menus.darkMode
    - plugins.articlePage
  options:
    iconPrefix: fa-light PETERRIVE
    articleShowLink: true
  plugins:
    navigation: 
      - {id: 'left', name: '转到上一页', icon: 'fa-light fa-arrow-left PETERRIVE', event: 'history.back()', group: 'navigation'}
      - {id: 'right', name: '转到下一页', icon: 'fa-light fa-arrow-right PETERRIVE', event: 'history.forward()', group: 'navigation'}
      - {id: 'redo', name: '刷新当前页面', icon: 'fa-light fa-redo PETERRIVE', event: 'window.location.reload()', group: 'navigation'}
      - {id: 'home', name: '回到首页', icon: 'fa-light fa-home PETERRIVE', link: '/', group: 'navigation'}
    articlePage:
      - {id: 'printMode', name: '打印页面', icon: 'fa-light fa-print TURQUOISE', event: 'printMode', group: 'articlePage'}
      - {id: 'readMode', name: '阅读模式', icon: 'fa-light fa-book-open EMERALD', event: 'readMode', group: 'articlePage'}
    inputBox:
      - {id: 'copyPaste', name: '粘贴文本', icon: 'fa-light PETERRIVE fa-paste', event: 'copyPaste', group: 'inputBox'}
      - {id: 'copyAll', name: '全选文本', icon: 'fa-light PETERRIVE fa-object-ungroup', event: 'copyAll', group: 'inputBox'}
      - {id: 'copyCut', name: '剪切文本', icon: 'fa-light PETERRIVE fa-cut', event: 'copyCut', group: 'inputBox'}
    seletctText:
      - {id: 'copyText', name: '复制文本', icon: 'fa-light PETERRIVE fa-copy', event: 'copyText', group: 'seletctText'}
      #- {id: 'html2md', name: '复制为 MD', icon: 'fa-light PETERRIVE fa-file-signature', event: 'volantis.rightmenu.html2md()', group: 'seletctText'}
      - {id: 'searchWord', name: '站内搜索', icon: 'fa-light PETERRIVE fa-search', event: 'OpenSearch(__text__)', group: 'seletctText'}
      - {id: 'bingSearch', name: '必应搜索', icon: 'fa-light PETERRIVE fa-search', event: 'window.open(`https://cn.bing.com/search?q=${__text__}`)', group: 'seletctText'}
    elementCheck:
      - {id: 'openTab', name: '新标签页打开', icon: 'fa-light PETERRIVE fa-external-link-square-alt', event: 'window.open(__link__)', group: 'elementCheck'}
      - {id: 'copyLink', name: '复制链接地址', icon: 'fa-light PETERRIVE fa-link', event: 'copyLink', group: 'elementCheck'}
    elementImage:
      - {id: 'copyImg', name: '复制图片文件', icon: 'fa-light PETERRIVE fa-image', event: 'copyImg', group: 'elementImage'}
  menus:
    links:
      - {id: 'friends', name: '我的朋友们', icon: 'fa-light fa-flower-daffodil AMETHYST', link: '/page/friends/', group: 'link'}
      - {id: 'archive', name: '文章归档', icon: 'fa-light fa-globe-asia CONCRETE', link: '/archives/', group: 'link'}
      - {id: 'categorie ', name: '文章分类', icon: 'fa-light fa-folder-open ALIZARIN', link: '/categories/', group: 'link'}
      - {id: 'about', name: '关于我', icon: 'fa-light fa-gingerbread-man WISTERIA', link: '/page/about/', group: 'link'}
      - {id: 'info', name: '留言板', icon: 'fa-light fa-object-group ALIZARIN', link: '/page/info/', group: 'link'}
    darkMode: 
      - {id: 'darkMode', name: '暗黑模式', icon: 'fa-light fa-eclipse-alt WISTERIA', event: 'volantis.dark.toggle()', group: 'darkMode'}
    prevNext:
      - {id: 'prev', name: '查看上一篇', icon: 'fa-light fa-angles-left PETERRIVE', event: "volantis.rightmenu.jump('prev')", group: 'prevNext'}
      - {id: 'next', name: '查看下一篇', icon: 'fa-light fa-angles-right PETERRIVE', event: "volantis.rightmenu.jump('next')", group: 'prevNext'}

search:
  enable: true
  algolia:
    searchAsYouType: false
    placeholder: '输关键词后「回车」搜索' # The placeholder text of the input.
  meilisearch:
    placeholder: 'Search...'
    searchKey: '162d226211d1dd3c5a3dfedbefcb1d349c5d84f00ecc76397677879d8850c317'
    indexName: 'hexo'
    hostUrl: 'https://search.szyink.com/'

custom_css:
  toc_smooth: true # TOC 目录平滑滚动效果
  cursor:
    enable: false
    text: https://static.szyink.com/common/cursor/text.png
    pointer: https://static.szyink.com/common/cursor/pointer.png
    default: https://static.szyink.com/common/cursor/left_ptr.png
    not-allowed: https://static.szyink.com/common/cursor/circle.png
    zoom-out: https://static.szyink.com/common/cursor/zoom-out.png
    zoom-in: https://static.szyink.com/common/cursor/zoom-in.png
    grab: https://static.szyink.com/common/cursor/openhand.png
  scrollbar:
    size: 4px
    border: 2px  
  fontsize:
    root: 16px
  body:
    effect: [floatable] # [shadow, floatable, blur]  
  navbar:
    effect: [floatable]
    #height: 0px
  sidebar:
    effect: [floatable] # [shadow, floatable, blur]  
  max_width: 1080px
  fontfamily:
    logofont:
      fontfamily: 'LXGW WenKai Screen,PingFang SC,Microsoft YaHei,SimHei,Arial,SimSun'
      url: ''
    bodyfont:
      fontfamily: 'LXGW WenKai Screen,-apple-system,SF UI Text,Arial,PingFang SC,Hiragino Sans GB,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif'
      url: ''
    codefont:
      fontfamily: 'LXGW WenKai Screen,Source Code Pro,DejaVu Sans Mono,Ubuntu Mono,Anonymous Pro,Droid Sans Mono,Menlo,Monaco,Consolas,Inconsolata,Courier,monospace,PingFang SC,Microsoft YaHei,sans-serif'
      url: ''

open_graph:
  image: icon/android-chrome-192x192.png

structured_data:
  enable: false
  # 以下是覆盖配置, 默认配置见 scripts/helpers/structured-data/lib/config.js
  data:
    person:
      sns:
        - https://github.com/inkss
    logo:
      path: icon/android-chrome-192x192.png
      width: 192
      height: 192

